export const editPageConfig = {
  heightMin: 300,
  placeholderText: 'Write something awesome...',
  theme: 'dark',
  toolbarButtons: [
    'fontFamily',
    '|',
    'fontSize',
    '|',
    'paragraphFormat',
    '|',
    'bold',
    'italic',
    'underline',
    'undo',
    'redo',
    'codeView',
  ],
  fontFamilySelection: true,
  fontSizeSelection: true,
  paragraphFormatSelection: true,
}
